# Generated by Django 2.2.3 on 2019-08-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='name',
        ),
        migrations.AddField(
            model_name='priority',
            name='field_name',
            field=models.CharField(default='none', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
