# Generated by Django 2.2.3 on 2019-08-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_priority_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['name', 'image_filename', 'image_caption', 'group', 'formula', 'category', 'strunz_classification', 'mohs_scale_hardness', 'luster', 'color', 'specific_gravity', 'cleavage', 'diaphaneity', 'crystal_habit', 'streak', 'optical_properties', 'refractive_index', 'unit_cell', 'crystal_symmetry']},
        ),
    ]
