# Generated by Django 2.2.3 on 2019-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190802_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['name']},
        ),
    ]
