# Generated by Django 2.2.3 on 2019-08-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190802_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
